### ISSUE TITLE
Pass the specific request through the proxy

### ISSUE THREAD

**Issue by ticketsvl** [allfro/pymiproxy#14]
Hi. First, thanks for a great tool.
Maybe a noob question and it's not an issue, but can you help?

I want to pass-through an a request to specified host without mitm it. If host == "somehost.com" send it in a usual way.

So, AsyncMitmProxy summon MitmProxy class at very beginning listening the port. My app has connected to proxy and it had already initialized with modified ca_file.  Than it goes to ProxyHandler class and target host can be found it self.path.

Should I create copy of MitmProxy class on different port to detect target host or it can be done in more simple way?
Thanks!

**Comment by allfro** [comment]
Hi @ticketsvl,

What you are asking for is simply not possible. If the request reaches the proxy then it is already at a stage where it cannot be "unproxied". An alternative approach is to have the client-side control this behaviour. For example, FoxyProxy allows you to define rules that determine whether a request is proxied.
